
    let foodData=[
    {
        image : "https://jimmys.vn/wp-content/uploads/2021/06/half-pizza-prod-image.jpg",
        text:"Pizza"
    },
    {
        image :"https://previews.123rf.com/images/ra3rn/ra3rn1210/ra3rn121000088/15703921-twelve-different-pieces-of-cake-isolated-on-white-background-top-view-close-up.jpg",
        text:"Cake"
    },
    {
        image :"https://www.shutterstock.com/image-photo/dum-handi-chicken-biryani-prepared-600nw-2000023556.jpg",
        text:"Biryani"
    },
    {
        image :"https://t4.ftcdn.net/jpg/06/68/04/05/360_F_668040516_RU9N0U3DOMsquogpDuHd4nFVxdAgVDIw.jpg",
        text:"Thali"
    },
    {
        image :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-5l26RQRKKZ1hJp_l1Saok8GMpMrSKWtLAzTP8kiBOdQARmTiQiyINDFCU4cnbpSASRw&usqp=CAUg",
        text:"Fried Rice"
    },
    {
        image :"https://img.freepik.com/premium-photo/grill-roast-bbq-chicken-leg-isolated-white-background_126277-265.jpg",
        text:"Chicken"
    },
    {
        image :"https://static.vecteezy.com/system/resources/previews/004/158/458/large_2x/fried-chinese-traditional-spring-rolls-food-isolated-on-white-background-photo.jpg",
        text :"Rolls"
    },
    {
        image :"https://ts2.mm.bing.net/th?q=Burger%20King%20Chicken%20Burger",
        text:"Burger"
    },
    {
        image :"https://www.shutterstock.com/image-photo/two-halves-fresh-club-sandwich-600nw-1705618366.jpg",
        text:"Sandwich"
    }
]

let cityName=[
    {
        city:"Agra"
    },
    {
        city:"Ahmedabad"
    },
    {
        city:"Ajmer"
    },
    {
        city:"Amtritsar"
    },
    {
        city:"Alappuzha"
    },
    {
        city:"Allahabad"
    },
    {
        city:"Amravati"
    },
    {
        city:"Aurangabad"
    },
    {
        city:"Bengaluru"
    },
    {
        city:"Bhopal"
    },
    {
        city:"Bhubaneswar"
    },
    {  
        city:"Chandigarh"
    },
    {
        city:"Chennai"
    },
    {
        city:"Coimbatore"
    },
    {   
        city:"Chuttack"
    },
    {
        city:"Darjeeling"
    },
    {
        city:"Dehradun"
    },
    { 
        city:"Delhi NCR"
    },
    {     
        city:"Dharamshala"
    },
    {      
        city:"Gangtok"
    },
    {      
        city:"Goa"
    },
    {      
        city:"Gorakhpur"
    },
    {      
        city:"Guntur"
    },
    {      
        city:"Guwahati"
    },
    {      
        city:"Gwalior"
    },
    {      
        city:"Haridwar"
    },
    {      
        city:"Hyderabad"
    },
    {     
        city:"Indore"
    },
    {      
        city:"Jabalpur"
    },
    {      
        city:"Jaipur"
    },
    {     
        city:"Jalandhar"
    },
    {     
        city:"Jammu"
    },
    {      
        city:"Jamnagar"
    },
    {     
        city:"Janshedpur"
    },
    {      
        city:"Jhansi"
    },
    {      
        city:"Jodhpu"
    },
    {      
        city:"Junagadh"
    },
    {      
        city:"Kanpur"
    },
    {     
        city:"Khajuraho"
    },
    {
     
        city:"Khamgaon"
    },
    {     
        city:"Kharagpur"
    },
    {     
        city:"Kochi"
    },
    {     
        city:"Kolhapur"
    },
    {      
        city:"Kolkata"
    },
    {     
        city:"Kota"
    },
    {      
        city:"Lucknow"
    },
    {
        city:"Ludhiana"
    },
    {
        city:"Madurai"
    },
    {
        city:"Manali"
    },
    {
        city:"Mangalore"
    },
    {
        city:"Manipal"
    },
    {
        city:"Meerut"
    },
    {
        city:"Mumbai"
    },
    {
        city:"Mussoorie"
    },
    {
        city:"Mysore"
    },
    {
        city:"Nagpur"
    },
    {
        city:"Nainital"
    },
    {
        city:"Nashik"
    },
    {
        city:"Neemrana"
    },
    {
        city:"Ooty"
    },
    {
        city:"Palakkad"
    },
    {
        city:"Patiala"
    },
    {
        city:"Puducherry"
    },
    {
        city:"Pune"
    },
    {
        city:"Pushkar"
    },
    {
        city:"Raipur"
    },
    {
        city:"Rajkot"
    },
    {
        city:"Ranchi"
    },
    {
        city:"Rishikesh"
    },
    {
        city:"Salem"
    },
    {
        city:"Sheemla"
    },
    {
        city:"Siliguri"
    },
    {
        city:"Shrinagar"
    },
    {
        city:"Surat"
    },
    {
        city:"Thrissur"
    },
    {
        city:"Trichy"
    },
    {
        city:"Trivandrum"
    },
    {
        city:"Udaipur"
    },
    {
        city:"Vadodara"
    },
    {
        city:"Varanasi"
    },
    {
        city:"Vellore"
    },
    {
        city:"Vijayawada"
    },
    {
        city:"Visakhapatannm"
    }   
]

let cityfoodData=[
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Pizza",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Burger",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Salad",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Sandwich",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Rice",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Pizza",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Rice",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Burger",
        price:'₹250'
    },
    {
        img:'https:images.unsplash.com/photo-1493770348161-369560ae357d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fHw%3DD"',
        text:"Sandwich",
        price:'₹250'
    }
]

export {foodData, cityName,cityfoodData};
